### ISSUE TITLE
Возможные улучшения

### ISSUE THREAD

**Issue by neonick** [gypsygoose/bikees#1]
https://github.com/gypsygoose/bikees/blob/3ebadb066a13e7731868b42094ec267ea3136195/source/index.pug#L18

```
a.logo__link(href="#") 
  span Bikees
  span.logo__dot .
```

**Comment by neonick** [comment]
https://github.com/gypsygoose/bikees/blob/master/source/less/index.less#L13

Woff2 по-дефолту (он на 30% легче), woff – как фолбек

**Comment by neonick** [comment]
В сборке нужен какой-нибудь css-minifier, csso, например. Можно добавить его как плагин Webpack или добавить как плагин PostCSS и заодно поучиться настраивать его конфиг, он несложный и можно докинуть еще разных postcss-плагинов.

**Comment by neonick** [comment]
Сделай отдельный темплейт для шапки, футера и вообще для повторяющихся частей и подключай их инклудом (include includes/head.pug). Когда тебе нужно поменять будет ссылку в футере, например, ты будешь это править в одном файле, а не на всех страницах руками. Это общий принцип: всё что используется больше одного раза — во внешний файл.

**Comment by neonick** [comment]
font-family нужно использовать обязательно с похожим системным фолбеком и указанием начертания. т.е. вместо 

 ```font-family: "Open Sans";```

нужно

```
@main-font: "Open Sans", Arial, sans-serif;

...

.class {
   font-family: @main-font;
}
```

**Comment by neonick** [comment]
Спорный вопрос, но я бы не использовал единицы измерения `em`. Их сложно в голове конвертировать в `px` и не так читабельно. Лучше пока без них обойтись, их можно использовать в будущем в чрезвычайно гибких адаптивных макетах.

**Comment by neonick** [comment]
Рекомендую сразу выработать хороший стиль написания кода.
1) Минимум — изучить вот этот https://github.com/stylelint/stylelint-config-standard
2) Максимум — подключить stylelint, добавить в него stylelint-config-standard и добавить в редактор плагин stylelint

**Comment by neonick** [comment]
Спорный момент, но мне лично удобнее использовать медиа-выражения сразу в описании селектора, например так (пишу в SCSS синтаксисе, LESS возможно поддерживает подобное):
```
.class {
  width: 100%;
  
  @media screen and (max-width: 1024px) {
    width: 80%;
  }

  @media screen and (max-width: 767px) {
    width: 50%;
  }

}
```
Попробуй, может тебе будет удобнее.

**Comment by neonick** [comment]
У тебя какой-то странный index.js тут :)

**Comment by neonick** [comment]
Внимательно смотри за используемыми изображениями.
Нужен в сборке оптимизатор картинок. Если его нет, прогоняй руками чере https://tinyjpg.com/ например. 
Я покидал туда картинки, сжимает на 60-70% меньше, а это очень важно.

**Comment by gypsygoose** [comment]
Все готово.
1. Исправил в pug вложенность тэгов в одну строку.
2. Сконвертировал шрифты в woff2, оставил woff в качестве фолбека.
3. Добавил в проект PostCSS, как лоадер webpack'а. Подключил к нему csso, в качастве минификатора css, и autoprefixer.
4. Перенес повторяющуюся часть сайта в отдельный pug шаблон. Стили футера, хедера и базовые стили также перенес в отдельные файлы.
5. Добавил системный фоллбэк для шрифтов.
6. Поставил в Sublime stylelint (extends: 'stylelint-config-standard'), jshint и pug-lint. Исправил синтаксические ошибки.
7. Перенес media-queries в описание селекторов. Так и правда оказалось гораздо удобнее.
8. Добавил в webpack оптимизатор изображений.
